#' Add an iptw column to a dataframe for a specific variable used as grouping factor
#'
#' This function add Inverse Probability of Treatment Weighting (IPTW) columns
#' to the input data.frame object, you get a "PSassign" column of the actual PS
#' for the treatment indicated and its relative iptw as column too
#'
#' @param data: the data.frame object for the analysis, output of add_PS()
#' @param tx_name: the column name of the treatment variable
#' @param tx_levels: the levels of the treatment variable (default: levels() of the column, it will be converted to factor() if is not)
#' @param iptw: the name of the added column with IPTW values
#' @param ps_prefix: the prefix for PS columns generated by add_PS() (default: "PS_")
#' @return A data.frame object which is the original data.frame with a PSassign and IPTW column added
add_IPTW <- function( data, tx_name, tx_levels = NULL, iptw = 'iptw', ps_prefix = "PS_") {
  ### if tx_levels are not specified it assign to the levels of the passed variable
  if (is.null(tx_levels)) {
    if (is.factor(data[[tx_name]])) {
      tx_levels <- levels( data[[tx_name]] )
    } else {
      tx_levels <- levels( factor(data[[tx_name]]) )
    }
  }
  ### convert the treatment variable to numeric as 1/0 for each level
  dfAssign <- as.data.frame(lapply(tx_levels, function(tx_k) {
    as.numeric(data[tx_name] == tx_k)
  }))
  ### assign names combining tx_name and tx_levels
  colnames(dfAssign) <- paste0(tx_name, tx_levels)
  ### get names of variables in which PS were stored
  psVars <- paste0( ps_prefix, tx_levels )
  ### create a PSassign column in data.frame which multiplies sum of PS * 1/0 of the variable
  #   basically keeping PS of the actual treatment level of the sample
  data[['PSassign']] <- rowSums(data[psVars] * dfAssign)
  ### add IPTW column which is exp(-log(PS))
  data[[iptw]] <- exp(- log(data[['PSassign']]))
  return(data)
}
